name: Reuseble Deploy
on:
  # This defines that the workflow can be called by other workflows
  workflow_call:   
    inputs:        
      artifacts-name:
        description: 'Name of the deployable artifacts file'
        required: false 
        default: 'dist'
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifacts@v3
        with:
          name: ${{ inputs.artifacts-name }}
      - name: List file
        run: ls
      - name: Output information
        run: echo "Deploying"
