name: Reuseble Deploy
on: 
  # This workflow can be called by other workflows
  workflow_call:
    # The name of the input variable
    inputs:
      artifacts-name:
      description: Name of the deployble artifacts file
      # Indicates this input is optional
      required: false 
      default: dist
      type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifacts@v3
        with:
          name: ${{ inputs.artifacts-name }}
      - name: List file
        run: ls
      - name: Output information
        run: echo "Deploying"
