name: Reuseble Deploy
on:
  # This defines that the workflow can be called by other workflows
  workflow_call:   
    inputs:        
      artifacts-name:
        description: 'Name of the deployable artifacts file'
        required: false 
        default: 'dist'
        type: string
    # Defines outputs that can be used by the calling workflow
    outputs:
      result:
        description: Result of the deployment
        # Sets the value of the output to the result from the deploy job
        value: ${{ jobs.deploy.outputs.outcomes }}
jobs:
  deploy:
    outputs:
      outcomes: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          # The name of the artifact to download is provided by the input "artifacts-name"
          name: ${{ inputs.artifacts-name }}
      - name: List file
        run: ls
      - name: Output information
        run: echo "Deploying"
        # Step to set the output result of the job
      - name: Set result output
        id: set-result
        # Sets the output variable "step-result" to "success"
        run: echo "step-result=success" >> $GITHUB_OUTPUT
